// Current available options
export let current_well_colors_import = {
    'White': true,
    'Erase': true,
    // Lab
    'sfGFP': true,
    'mRFP1': true,
    'mKO2': true,
    'Venus': true,
    'mKate2_TF': false,
    'Azurite': false,
    'mCerulean3': false,
    'mClover3': false,
    'mJuniper': false,
    'mTurquoise2': true,
    'mBanana': false,
    'mPlum': false,
    'Electra2': true,
    'mWasabi': false,
    'mScarlet_I': true,
    'mPapaya': false,
    'eqFP578': false,
    'dTomato': false,
    'DsRed': false,
    'mKate2': false,
    'EGFP': false,
    'mRuby2': false,
    'TagBFP': false,
    'mChartreuse_TF': false,
    'mLychee_TF': false,
    'mTagBFP2': false,
    'mEGFP': false,
    'mNeonGreen': false,
    'mAzamiGreen': false,
    'mWatermelon': false,
    'avGFP': false,
    'mCitrine': false,
    'mVenus': false,
    'mCherry': false,
    'mHoneydew': false,
    'TagRFP': false,
    'mTFP1': false,
    'Ultramarine': false,
    'ZsGreen1': false,
    'mMiCy': false,
    'mStayGold2': false,
    'PA_GFP': false,
    'eforRed': false,
}

export let source_384_well_colors = {
    'sfgfp': 'A',
    'electra2': 'B',
    'mrfp1': 'C',
    'mwasabi': 'D',
    'mko2': 'E',
    'mscarlet_i': 'F',
    'venus':'G',
    'mkate2_tf': 'H',
    'azurite': 'I',
    'mcerulean3': 'J',
    'mclover3': 'K',
    'mbanana': 'L',
    'mjuniper': 'M',
    'mplum': 'N',
    'mturquoise2': 'O',
    'mpapaya': 'P',
}

// PREVIOUS VERSION FOR REFERENCE
// export let source_384_well_colors = {
//     'sfgfp': 'A',
//     'electra2': 'B',
//     'mrfp1': 'C',
//     'mwasabi': 'D',
//     'mko2': 'E',
//     'mscarlet_i': 'F',
//     'venus':'G',
//     'azurite': 'I',
//     'mclover3': 'K',
//     'mjuniper': 'M',
//     'mturquoise2': 'O',
// }

// export let current_well_colors_import = {
//     'White': true,
//     'Erase': true,
//     // Lab
//     'sfGFP': true,
//     'mRFP1': true,
//     'mKO2': true,
//     'Venus': true,
//     'mKate2_TF': true,
//     'Azurite': true,
//     'mCerulean3': true,
//     'mClover3': true,
//     'mJuniper': true,
//     'mTurquoise2': true,
//     'mBanana': true,
//     'mPlum': true,
//     'Electra2': true,
//     'mWasabi': true,
//     'mScarlet_I': true,
//     'mPapaya': true,
//     'eqFP578': true,
//     'tdTomato': true,
//     'DsRed': true,
//     'mKate2': true,
//     'EGFP': true,
//     'mRuby2': true,
//     'TagBFP': true,
//     'mChartreuse_TF': true,
//     'mLychee_TF': true,
//     'mTagBFP2': true,
//     'mEGFP': true,
//     'mNeonGreen': true,
//     'mAzamiGreen': true,
//     'mWatermelon': true,
//     'avGFP': true,
//     'mCitrine': true,
//     'mVenus': true,
//     'mCherry': true,
//     'mHoneydew': true,
//     'TagRFP': true,
//     'mTFP1': true,
//     'Ultramarine': true,
//     'ZsGreen1': true,
//     'mMiCy': true,
//     'mStayGold2': true,
//     'PA_GFP': true,
// }

// WELL COLORS (FPBASE)
// export let well_colors = {
//     'sfGFP' : ' #00ff00',
//     'mRFP1' : ' #fc0000',
//     'mKO2' : ' #ff9c00',
//     'mKate2': ' #9b0000',
//     'EGFP': ' #00ff26',
//     'mTurquoise2': ' #00adff',
//     'Venus': ' #d3ff00',
//     'mRuby2': ' #ff1300',
//     'Azurite': ' #0023ff',
//     'TagBFP': ' #0056ff',
//     'mCherry': ' #f70000',
//     'mKate2_TF': ' #9b0000',
//     'mChartreuse_TF': ' #00ff00',
//     'mLychee_TF': ' #ff2300',
//     'mTagBFP2': ' #0047ff',
//     'mTagBFP2': ' #0047ff',
//     'mCerulean3': ' #00b2ff',
//     'mEGFP': ' #00ff26',
//     'mClover3': ' #1dff00',
//     'mNeonGreen': ' #19ff00',
//     'mAzamiGreen': ' #00ff3f',
//     'mWatermelon': ' #12ff00',
//     'mJuniper': ' #00b2ff',
//     'avGFP': ' #00ff0c',
//     'DsRed': ' #ff5600',
//     'eqFP578': ' #ff6900',
//     'mCitrine': ' #d6ff00',
//     'mVenus': ' #cfff00',
//     'mHoneydew': ' #ffa800',
//     'mBanana': ' #ffcc00',
//     'tdTomato': ' #ff5e00',
//     'mPlum': ' #c00000',
//     'TagRFP': ' #ff5200',
//     'Electra2': ' #0047ff',
//     'mTFP1': ' #00ffe5',
//     'mWasabi': ' #00ff0c',
//     'mScarlet_I': ' #ff2f00',
//     'Ultramarine': ' #e10000',
//     'mPapaya': ' #fffb00',
//     'ZsGreen1': ' #00ff3f',
//     'mMiCy': ' #00ffb2',
//     'mStayGold2': ' #00ff0c',
//     'PA_GFP': ' #00ff0c',
//     'White': ' #ffffff',
//     'Erase': ' #e5e5e5',
// }

// WELL COLORS (REALITY)
export let well_colors = {
    'sfGFP' : ' #1fea5c' ,
    'mRFP1' : ' #8f2438',
    'mKO2' : ' #ffef7a',
    'mKate2': ' #44203D',
    'EGFP': ' #0C5EC0',
    'mTurquoise2': ' #13AEA7',
    'Venus': ' #6ad500',
    'mRuby2': ' #953E43',
    'Azurite': ' #3867ae',
    'TagBFP': ' #0B58C1',
    'mCherry': ' #9f57a0',
    'mKate2_TF': ' #74274B',
    'mChartreuse_TF': ' #735a9a',
    'mLychee_TF': ' #E45741',
    'mTagBFP2': ' #1B60D1',
    'mCerulean3': ' #00636F',
    'mEGFP': ' #1EA862',
    'mClover3': ' #409945',
    'mNeonGreen': ' #3b8757',
    'mAzamiGreen': ' #04A966',
    'mWatermelon': ' #0F7449',
    'mJuniper': ' #1c978d',
    'avGFP': ' #104B53',
    'DsRed': ' #7C463E',
    'eqFP578': ' #151F4F',
    'mCitrine': ' #297A40',
    'mVenus': ' #5DD313',
    'mHoneydew': ' #24324B',
    'mBanana': ' #5F692D',
    'dTomato': ' #fc8b5b',
    'mPlum': ' #291c46',
    'TagRFP': ' #80474E',
    'Electra2': ' #1C58C6',
    'mTFP1': ' #03A185',
    'mWasabi': ' #009349',
    'mScarlet_I': ' #b9474b',
    'Ultramarine': ' #0F184C',
    'mPapaya': ' #83C603',
    'ZsGreen1': ' #0C9A68',
    'mMiCy': ' #00977F',
    'mStayGold2': ' #192660',
    'PA_GFP': ' #138A5C',
    'eforRed': ' #fe6587', 
    'White': ' #FFFFFF',
    'Erase': ' #E5E5E5',
}

export const old_well_colors = {
    'sfGFP_mKO2': '#ffd000', // yellow-200
    'Red' : '#fca5a5', // red-300
    'Green' : '#86efac', // green-300
    'Orange' : '#ffcc80', // orange-200
    'White': '#ffffff',
}